### ISSUE TITLE
[Suggestion] Target disguise placeholder

### ISSUE THREAD

**Issue by SlyyJacob** [internetpolice-eu/LibsDisguisesPAPI#2]
Would it be possible to add target entity disguise placeholder? I am trying to get the disguise into a variable to use later on, but so far I haven't found a placeholder for that use.

**Comment by Muspah** [comment]
I'm not sure what you're looking for, just to clarify, which value do you need as a placeholder exactly? :)

**Comment by SlyyJacob** [comment]
Actually nevermind, found a way around it by using the %libsdisguises_disguised_as% ^^

**Comment by CdeJong** [comment]
Glad you found another solution. I take it you want the entity type? I can add that for you if you want.

**Comment by SlyyJacob** [comment]
@CdeJong Yes, please, that would be great! I realised the placeholder works only for players, as soon as I want to use it within entity, it doesn't return a value.

Edit: To explain this better - I am using MythicMobs where I have mobs using a disguise. Say I have a stray using polarbear disguise (for mechanic purposes). I have made a polymorph spell, which disguises said mob into a pig/sheep. Now I need to disguise it back to it's original disguise - I can set a variable with the value, but I am missing the value now.

**Comment by CdeJong** [comment]
I don't think it's possible, because I wouldn't know how to get that entity without requesting nearby mobs of a player thousands of times. For this it is better to use the API from libsdisguises or from MysticMobs in your own plugin/addon. (I am not familiar with MysticMobs)
